kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "python-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/vgonzalezo/openshift-python-example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile